<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPDqoyrS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPDqoyrS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPDqoyrS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPDqoyrS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPDqoyrS\App_KernelDevDebugContainer([
    'container.build_hash' => 'PDqoyrS',
    'container.build_id' => 'd198391d',
    'container.build_time' => 1707209419,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPDqoyrS');
