<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxPOaZx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxPOaZx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxPOaZx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxPOaZx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxPOaZx\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxPOaZx',
    'container.build_id' => '4536f100',
    'container.build_time' => 1707128256,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxPOaZx');
